### ISSUE TITLE
radicle-org-node gets stuck, ignoring traffic, spinning 2 cpu cores

### ISSUE THREAD

**Issue by kermit4** [radicle-dev/radicle-link#765] opened 2021-08-19 19:24 UTC
netstat shows unread packets accumulating
top shows 200% CPU usage

the last line in logs was:

Aug 19 19:18:34.619  INFO ureq::unit: sending request POST https://api.thegraph.com/subgraphs/name/radicle-dev/radicle-orgs    

this is at commit 0a4a3954684daea7693d385a2f902f34f4ecf766
release build

Linux 4.18.0-305.3.1.el8.x86_64
CentOS Linux release 8.4.2105

**Comment by kermit4** [comment] 2021-08-19 19:33
The CPU usage may be unrelated as it does that at times it is responding to network traffic.

**Comment by kim** [comment] 2021-08-19 19:50
I’m not sure what a radicle org node is, but this is probably a duplicate of #734

**Closed by kim** 2021-08-19 19:50 UTC
