### ISSUE TITLE
Unreliable project replication

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-link#602] opened 2021-04-12 17:12 UTC
When queueing multiple projects to be replicated from a seed node, only a couple get replicated. The rest stay in the queue until the client and seed is restarted.

Steps to reproduce:

1. start [Upstream](https://github.com/radicle-dev/radicle-upstream/commit/47ced24620841fb74d35c9862dc8c9617fb7366e) and a [seed node](https://github.com/radicle-dev/radicle-bins/commit/38386e3d3097108623a503c2b8b2617dc92c1309)
2. replicate 5-10 projects from a seed node (e.g. setzling.radicle.xyz)

Expected outcome: all projects are replicated after a while without restarting either the client or the seed.
Actual outcome: some projects stay in the queue forever.

<img width="70%" alt="Screenshot 2021-04-12 at 19 09 22" src="https://user-images.githubusercontent.com/158411/114433858-9888e080-9bc2-11eb-8b59-b1569aa576af.png">

**Comment by alexjg** [comment] 2021-04-19 21:09
I've been digging a little to try and understand what's going on. I've been able to reproduce the issue with a local seed node and upstream. On my machine the seed stops replicating at 4 projects almost every time, occasionally at 5. Restarting the seed fixes the problem.

The path that causes this is the following:

1. We recieve a Gossip event with a new project URN
2. This falls through to `radicle_seed::Node::handle_event`, then `radicle_seed::Node::track_project`
3. This calls `librad::net::peer::retrying`, which is a wrapper around `fetcher::retrying`. Note that this is slightly different on `master`, I'm working from `xla/bumps`
4. `fetch::retrying` starts by calling `build` on it's argument `BuildFetcher`, which in this case is an instance of `librad::git::storage::fetcher::PeerToPeer`
5. This (after some indirection) calls `librad::git::storage::fetcher::imp::Fetcher::with_url`, which looks like this:

```rust
pub fn with_url(
    storage: &'a Storage,
    url: Url,
    urn: Urn,
    remote_peer: PeerId,
) -> Result<Self, git2::Error> {
    tracing::info!("GET REMOTE");
    let mut remote = storage.as_raw().remote_anonymous(url.as_str())?;
    tracing::info!("GOT REMOTE");
    remote.connect(git2::Direction::Fetch)?;
    tracing::info!("CONNECT");
```

The `remote.connect(..)` line is where we hang, we never see the `"CONNECT"` line in the logs.

`remote.connect` is a call to `libgit`, but it's not the end of the line. We've registered a custom handler with `libgit` so we eventually end up back in our codebase.

1. The git transport eventually ends up calling `librad::net::protocol::State::open_stream`
2. `open_stream` checks if we have an existing connection (`librad::net::quic::connection::Connection`) to the remote and either uses that or opens one. So far I have always observed an existing connection.
3. Once the connection is found we call `Connection::open_bidi`, which looks like this (modulo tracing calls which I have added):

```rust
pub async fn open_bidi(&self) -> Result<BidiStream> {
    tracing::info!("Opening bidi");
    let (send, recv) = self.conn.open_bi().await.map_err(|e| {
        self.track
            .disconnect(&self.id(), CloseReason::ConnectionError);
        e
    })?;
    tracing::info!("Opened bidi");
    self.tickle();
    tracing::info!("Tickled");
```

This function hangs on `self.conn.open_bi`, i.e I never see the `"Opened bidi"` line.

`self.conn` is an instance of `quinn::Connection`. `quinn::Connection::open_bi` returns an instance of `OpenBi`, which implements future thusly (again module tracing lines I have added):

```rust
/// A future that will resolve into an opened outgoing bidirectional stream
pub struct OpenBi<S>
where
    S: proto::crypto::Session,
{
    conn: ConnectionRef<S>,
    state: broadcast::State,
}


fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
    let this = self.get_mut();
    let mut conn = this.conn.lock("OpenBi::next");
    if let Some(ref e) = conn.error {
        return Poll::Ready(Err(e.clone()));
    }
    if let Some(id) = conn.inner.streams().open(Dir::Bi) {
        tracing::info!(id=?id, "Opened stream");
        let is_0rtt = conn.inner.side().is_client() && conn.inner.is_handshaking();
        drop(conn); // Release lock for clone
        return Poll::Ready(Ok((
            SendStream::new(this.conn.clone(), id, is_0rtt),
            RecvStream::new(this.conn.clone(), id, is_0rtt),
        )));
    } else {
        tracing::info!("Did not open stream");
    }
    conn.bi_opening.register(cx, &mut this.state);
    Poll::Pending
}
```

After adding the tracing lines I find that I get `"Did not open stream"` in the logs before we hang, but we never see anything after this, i.e the future is never polled again. In contrast in successful replications I see the `"Opened stream"` line and do not see the `"Did not open stream"`.

This implies we are either failing to drive a future correctly somewhere, or running into some kind of interaction with creating new streams in QUIC that I do not understand.

**Comment by alexjg** [comment] 2021-04-21 09:37
After some more investigation it appears that the reason we get stuck on `quinn::Connection::open_bi` is because we have hit the maximum number of open bidirectional streams for the connection. This is a feature of the QUIC protocol in which peers specify what the maximum number of open streams they support is. This number is specified by the peer as part of the connection setup and it is a protocol violation to open more than this maximum number. This maximum number is different for remote and peer initiated streams, what we are running into is the remote initiated stream limit. Therefore the limit is set by the Upstream client which is using the default Quinn limit of 100 open streams. We verified that this is the problem by increasing the max stream limit in Upstream which allowed us to replicate more than 12 projects before we observed the freeze up.

It seems unlikely that we would need 100 remotely initiated streams open, so our first order of business is to understand what these streams are, it seems likely we are failing to close streams when we no longer need them.

However, the remote initiated stream limit is set by the client, we cannot rely on it being reasonable, we should probably introduce a timeout in places where we wait for `librad::net::quic::Connection::open_bidi` to allow applications to close the connection if they continue to be blocked on opening new streams for too long.

Finally, there is a mechanism in QUIC to signal that a peer is blocked on the max stream limit, the remote can then decide whether to increase the limit. This is not implemented in Quinn (Quinn just ignores the `STREAMS_BLOCKED` frame) which is not a problem for Quinn<->Quinn interactions because Quinn increases the max stream limit every time a stream is closed by the remote, which means that in practice as long as the remote closes streams they will continue to be able to open new ones. However, other QUIC implementations may choose to handle stream limits differently by setting a low initial stream limit and then waiting for `STREAMS_BLOCKED` frames to increase the stream limit. This is probably not a concern for us as we're using Quinn on both ends but might be worth remembering for future interop cases.

**Comment by kim** [comment] 2021-04-21 10:22
Amazing and surprising and disturbing finds.

> it seems likely we are failing to close streams when we no longer need them.

I cannot find that we are leaking any streams, ie. failing to drop. The
behaviour of dropping a `SendStream` is, however, to continue re-transmitting
already written data if the remote end hasn't ack'ed it yet. I cannot find that
we're failing to flush either, so that leaves us with explicitly reset()'ing
streams once we're done (and handling resets on the receiving end).

**Closed** 2021-04-26 19:31 UTC
Labels: bug
