### ISSUE TITLE
Radicle Seed Node Can Be Crashed With Netcat

### ISSUE THREAD

**Issue by bonedaddy** [radicle-dev/radicle-link#533] opened 2021-02-27 10:02 UTC
# Overiew

Radicle seed nodes can be crashed with netcat, and can be tested using the [latest commit at this time](https://github.com/radicle-dev/radicle-bins/commit/090efeeeb7b4ca52dd068035874d46f11350e2a8). It is pretty simple to replicate and can be with the following:

```shell
$> nc -vu <seed-node-ip> <seed-node-ip>
# OR
$> nc -vzu <seed-node-ip> <seed-node-ip>
```

Honestly probably any combination of netcat commands can be used.

# Logs

```
thread 'tokio-runtime-worker' panicked at 'range end index 8 out of range for slice of length 0', /home/bonedaddy/.cargo/git/checkouts/quinn-572d2e5812b43165/babb07b/quinn-proto/src/packet.rs:517:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /home/bonedaddy/.cargo/git/checkouts/quinn-572d2e5812b43165/babb07b/quinn/src/endpoint.rs:215:42
stack backtrace:
   0:     0x5646f2e603d0 - std::backtrace_rs::backtrace::libunwind::trace::h448c56741b6011d3
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x5646f2e603d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2d26397c5720fdbb
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5646f2e603d0 - std::sys_common::backtrace::_print_fmt::h720a2f61f75b9f58
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5646f2e603d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d62bbfda6d5c836
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5646f2e848ac - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/core/src/fmt/mod.rs:1078:17
   5:     0x5646f2e59212 - std::io::Write::write_fmt::h16a9fe7680ac245c
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/io/mod.rs:1518:15
   6:     0x5646f2e62b15 - std::sys_common::backtrace::_print::h9ba51a6db618de7d
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5646f2e62b15 - std::sys_common::backtrace::print::h5f20e41c85e91716
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5646f2e62b15 - std::panicking::default_hook::{{closure}}::h5b7294ca19e8edab
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs:208:50
   9:     0x5646f2e627b8 - std::panicking::default_hook::hb3948d1f74b6ff4c
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs:227:9
  10:     0x5646f2e632b1 - std::panicking::rust_panic_with_hook::h55d23fef0ad751bc
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs:593:17
  11:     0x5646f2e62df7 - std::panicking::begin_panic_handler::{{closure}}::h56ae74c6dea6e141
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs:499:13
  12:     0x5646f2e6086c - std::sys_common::backtrace::__rust_end_short_backtrace::h3c4721f56689fae4
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5646f2e62d59 - rust_begin_unwind
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/panicking.rs:495:5
  14:     0x5646f2e82f31 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/core/src/panicking.rs:92:14
  15:     0x5646f2e82d53 - core::option::expect_none_failed::he492a18657d97593
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/core/src/option.rs:1268:5
  16:     0x5646f2896017 - <quinn::endpoint::EndpointDriver<S> as core::ops::drop::Drop>::drop::hf6609bd4b85ab246
  17:     0x5646f28fb91c - core::ptr::drop_in_place::hc5d5b5564867ff02
  18:     0x5646f292f8e4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb84101ac49335b80
  19:     0x5646f28c95bf - tokio::runtime::task::core::Core<T,S>::poll::h4b4cdf6c18b0e0af
  20:     0x5646f296ad83 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h73ea7e298eafc365
  21:     0x5646f282d1f9 - tokio::runtime::task::harness::Harness<T,S>::poll::h1afdddf231f629a2
  22:     0x5646f2cafd34 - std::thread::local::LocalKey<T>::with::h9444a050fb35ddab
  23:     0x5646f2cd2622 - tokio::runtime::thread_pool::worker::Context::run_task::h39c973c7a2016f80
  24:     0x5646f2cd1dd0 - tokio::runtime::thread_pool::worker::Context::run::h762cdead5d5aad8c
  25:     0x5646f2cb1af5 - tokio::macros::scoped_tls::ScopedKey<T>::set::hd875dbb86d2a131c
  26:     0x5646f2cd18a6 - tokio::runtime::thread_pool::worker::run::h1417bd1fc40d0fcc
  27:     0x5646f2ccaa00 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::he98d637d25b2387c
  28:     0x5646f2ccdef8 - tokio::runtime::task::core::Core<T,S>::poll::h107da107dc6ef3be
  29:     0x5646f2cd8b63 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9091a29b5eef434b
  30:     0x5646f2cb54b3 - tokio::runtime::task::harness::Harness<T,S>::poll::h2cbe9d612103df60
  31:     0x5646f2cb3e41 - tokio::runtime::blocking::pool::Inner::run::hd8ec43e27f0dc16b
  32:     0x5646f2cc39a8 - tokio::runtime::context::enter::heeaeebbf6b2fe24d
  33:     0x5646f2cafb0f - std::sys_common::backtrace::__rust_begin_short_backtrace::h345ab8543e43f4d8
  34:     0x5646f2cc23c0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8c63fce45e0be2a2
  35:     0x5646f2e6a0da - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9e7afb7a0a438236
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/alloc/src/boxed.rs:1307:9
  36:     0x5646f2e6a0da - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70c646c4271337a1
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/alloc/src/boxed.rs:1307:9
  37:     0x5646f2e6a0da - std::sys::unix::thread::Thread::new::thread_start::h35d2b8d36f210d02
                               at /rustc/25f6938da459a57b43bdf16ed6bdad3225b2a3ce/library/std/src/sys/unix/thread.rs:89:17
  38:     0x7fa69802a609 - start_thread
  39:     0x7fa697dfc293 - clone
  40:                0x0 - <unknown>
```

**Comment by kim** [comment] 2021-02-27 16:28
Thanks for reporting. The version of the seed node executable you are referring to is about to reach its EOL, can you reproduce this behaviour against the e2e test peer (`cargo run —bin ephemeral-peer`)?

**Comment by bonedaddy** [comment] 2021-02-28 06:59
What port does the ephemeral peer run on? I cant see to find its port:
![peernoport](https://user-images.githubusercontent.com/17089485/109410410-7597c980-7992-11eb-9573-13604e5fae64.png)

**Comment by kim** [comment] 2021-03-01 15:49
Yeah sorry, the info output got lost somehow. `lsof` will tell you the actual protocol port (in addition, the process binds 5353, and a random port connected to 9109).

I can't reproduce the behaviour, also reported in radicle-dev/radicle-bins#66, so closing. Feel free to reopen if you can still provoke a panic somehow.

**Closed by kim** 2021-03-01 15:49 UTC
