### ISSUE TITLE
net: quick reconnect will terminate both old and new connection

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-link#431] opened 2020-11-20 11:55 UTC
When quickly reconnecting (inside the keep alive max timeout) the old and new connection will be forcefully disconnected, likely because the old `recvd` stream when terminating with timed_out will hit this:

https://github.com/radicle-dev/radicle-link/blob/a3a6be979218311bf8df029003d5a851ca1329c8/librad/src/net/gossip.rs#L555-L556

**Comment by kim** [comment] 2020-11-20 20:05
Interestingly, I don't think there is a solution to this unless we invert the logic and reject new connections from the same peer, instead of ejecting existing ones. The problem is that we would need to wait until all futures which process streams of an existing connection have completed before we start processing the new one -- but that is not possible.

Perhaps the inverted logic is better anyway.

**Comment by xla** [comment] 2020-11-20 21:55
> Interestingly, I don't think there is a solution to this unless we invert the logic and reject new connections from the same peer, instead of ejecting existing ones. The problem is that we would need to wait until all futures which process streams of an existing connection have completed before we start processing the new one -- but that is not possible.

Would it help if we store some form of coordination primitive like a oneshot channel. Which when used to select in the same loop where the gossip messages are worked on, can be used to signal shutdown of the existing recv loop and helps determining that it has completed.

While punishing quick reconnects is not an unsound strategy it might impede heavily with spotty connectivity. Is there any possibility to "handover" the existing stream between connections? So when a peer reconnects the old one is removed and business continues as usual.

**Comment by kim** [comment] 2020-11-21 10:41
Before I respond with more thoughts: could you explain how this reconnection happens? Like, are you dropping the networking state, and then re-initialising it? Or is this something you observe with peers in steady state?

**Comment by xla** [comment] 2020-11-21 17:31
This happens when people restart Upstream, mostly when things get stuck (e.g. replication not working as expected). So the networking state is completely dropped. How contrive that is I don't know, I also can't say if it happens for steady peers, as we didn't have enough stored logs to contextualize.Definitely something worse investigating.

How does quic behave with network (wifi et al) interruptions, when the network state is preserved? Will this trigger the same connection duplication occur? Or will it, due to it's UDP genome, just continue with the same connection once packets roll on within the keep-alive period?

**Comment by kim** [comment] 2020-11-22 15:59
QUIC connection state is, just like TCP, maintained at both ends, and a connection is considered lost if and when either end detects that packets don't get ACKed anymore (modulo packet loss tolerance). There are indeed a few ways in which we can benefit from QUIC features such as roaming, connection migration, TLS1.3 session resumption... but, those are only applicable to a live QUIC `Endpoint`.

The issue at hand here seems that the initiator doesn't properly send a `CONNECTION_CLOSE` frame, or it gets lost somehow. The other end thus keeps the connection around until it detects enough packet loss to consider the connection dead. It is admittedly surprising that our ridiculousy low keep alive (we should really change that -- 30s is an appropriate value) doesn't make it converge faster, but then, keep in mind that it has to take normal packet loss into account.

I wouldn't be surprised if the problem goes away if we, instead of relying solely on Rust finalisers, issue an `Endpoint::close` somewhere.

**Comment by kim** [comment] 2020-11-22 17:09
> Is there any possibility to "handover" the existing stream between connections?

Yes, but that happens on connection-level -- connections are keyed by an ID, and may migrate to a different address, while the connection state stays the same. Yet that's the crux: both protocol and application state need to survive a migration, so this does not apply when the whole endpoint is shut down.

**Comment by kim** [comment] 2020-11-25 11:46
Believed to be fixed by #434

**Closed by kim** 2020-11-25 11:46 UTC
Labels: bug, networking
